[package]
name = "rimecraft-block"
version = "0.1.0"
edition = "2021"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft Block primitives"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-registry = { path = "../../util/registry" }
rimecraft-state = { path = "../state", optional = true }
serde = { version = "1.0", optional = true }

[features]
default = ["state"]
serde = ["dep:serde"]
state = ["dep:rimecraft-state"]

[lints]
workspace = true
