[package]
name = "rimecraft-interner"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Safe reference-counted interners"
repository = "https://codeberg.org/DM-Earth/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["data-structure"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
dashmap = "6.1"

[lints]
workspace = true
