[package]
name = "rimecraft-global-cx"
version = "0.1.0"
edition = "2021"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Rimecraft global context traits"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
serde = { version = "1.0", default-features = false, optional = true }
edcode2 = { path = "../../util/edcode2", package = "rimecraft-edcode2", optional = true }

[features]
default = ["std"]
std = []
serde = ["dep:serde"]
nbt = ["serde"]
edcode = ["dep:edcode2", "std"]

[lints]
workspace = true
