[workspace]
resolver = "2"
members = [
    "core",
    "primitives",
    "primitives/macros",
    # Utils
    "util/caches",
    "util/nbt_ext",
    "util/event",
    "util/edcode",
    "util/collections",
    "util/freezer",
]
