[package]
name = "rimecraft-ident-hash"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Hasher that doesn't hash at all"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["game-development"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]

[features]

[lints]
workspace = true
