[package]
name = "rimecraft-edcode-derive-tests"
version = "0.1.0"
edition = "2021"
authors = ["C191239 <zhushunzhong2025@i.pkuschool.edu.cn>"]
description = "Tests for rimecraft-edcode-derive"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["encoding"]

[badges]
maintenance = { status = "passively-maintained" }

[dev-dependencies]
rimecraft-edcode = { path = "../edcode", features = ["derive"] }

[lints]
workspace = true
