[package]
name = "rimecraft-registry"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft registry implementation"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["data-structures"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
parking_lot = "0.12"
serde = { version = "1.0", optional = true }
edcode2 = { path = "../../util/edcode2", package = "rimecraft-edcode2", optional = true }
ahash = "0.8"
typeid = "1.0"
local-cx = { path = "../local-cx", package = "rimecraft-local-cx" }
marking = { path = "../../util/marking", package = "rimecraft-marking", optional = true }

[features]
serde = ["dep:serde", "local-cx/serde"]
edcode = ["dep:edcode2", "local-cx/edcode"]
marking = ["dep:marking"]
marking-leaked = ["marking"]

[lints]
workspace = true
