[package]
name = "rimecraft-local-cx"
version = "0.1.0"
edition = "2021"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Rimecraft local context traits"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
global-cx = { path = "../global-cx", package = "rimecraft-global-cx" }
serde = { version = "1.0", default-features = false, optional = true }
erased-serde = { version = "0.4", optional = true }
edcode2 = { path = "../../util/edcode2", package = "rimecraft-edcode2", optional = true }
typeid = { version = "1.0", optional = true }
ahash = { version = "0.8", optional = true }

[features]
serde = ["dep:serde"]
erased-serde = ["dep:erased-serde"]
edcode = ["dep:edcode2"]
dyn-cx = ["dep:typeid", "dep:ahash"]

[lints]
workspace = true
