[package]
name = "rimecraft-chunk-palette"
version = "0.1.0"
edition = "2021"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft chunk palettes"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-packed-int-array = { path = "../../../util/packed-int-array" }
rimecraft-maybe = { path = "../../../util/maybe" }
rimecraft-edcode = { path = "../../../util/edcode", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
rimecraft-serde-update = { path = "../../../util/serde-update", optional = true }

[features]
edcode = ["dep:rimecraft-edcode"]
serde = ["dep:serde", "dep:rimecraft-serde-update"]

[lints]
workspace = true
