[package]
name = "rimecraft-world"
version = "0.1.0"
edition = "2021"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft world implementation"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-chunk-palette = { path = "./palette" }
rimecraft-registry = { path = "../registry" }
rimecraft-state = { path = "../state" }
rimecraft-block = { path = "../block" }
rimecraft-voxel-math = { path = "../../util/voxel-math" }
serde = { version = "1.0", features = ["derive"], optional = true }
parking_lot = "0.12"

[features]
default = ["serde"]
serde = ["dep:serde"]

[lints]
workspace = true
