[package]
name = "rimecraft-world"
version = "0.1.0"
edition = "2021"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft world implementation"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-global-cx = { path = "../global-cx" }
rimecraft-chunk-palette = { path = "../palette" }
rimecraft-registry = { path = "../../util/registry", features = ["serde"] }
rimecraft-state = { path = "../state" }
rimecraft-block = { path = "../block" }
rimecraft-fluid = { path = "../fluid" }
rimecraft-block-entity = { path = "../block-entity" }
rimecraft-voxel-math = { path = "../../util/voxel-math" }
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
rimecraft-edcode = { path = "../../util/edcode", optional = true }
parking_lot = "0.12"
fastnbt = "2.5"
ahash = "0.8"

[features]
default = ["edcode"]
edcode = ["dep:rimecraft-edcode", "rimecraft-chunk-palette/edcode"]

[lints]
workspace = true
