[package]
name = "rimecraft-serde-humanreadctl"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Serde human-readable controlling layers"
repository = "https://codeberg.org/DM-Earth/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["rust-patterns"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
serde = "1.0"

[features]

[lints]
workspace = true
