[package]
name = "rimecraft-dsyn"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "DSyn the descriptor set system"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["rust-patterns"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
ident-hash = { path = "../ident-hash", package = "rimecraft-ident-hash" }

[dev-dependencies]
typeid = "1.0"

[features]

[lints]
workspace = true
