[package]
name = "rimecraft-dsyn"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "DSyn the descriptor set system"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["rust-patterns"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
ident-hash = { path = "../ident-hash", package = "rimecraft-ident-hash" }
ahash = { version = "0.8", optional = true }
typeid = { version = "1.0", optional = true }

[dev-dependencies]
ahash = "0.8"
typeid = "1.0"

[features]
simple-registry = ["dep:ahash", "dep:typeid"]

[lints]
workspace = true
