[package]
name = "rimecraft-fluid"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft Fluid primitives"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-global-cx = { path = "../global-cx" }
rimecraft-registry = { path = "../registry" }
rimecraft-state = { path = "../state" }
rimecraft-maybe = { path = "../../util/maybe" }
rimecraft-block = { path = "../block" }

[features]

[lints]
workspace = true
