[package]
name = "rimecraft-fmt"
version = "0.1.0"
edition = "2021"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft formattings"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
rgb = "0.8"
regex = { version = "1.10", optional = true }

[features]
serde = ["dep:serde"]
# use `regex` crate instead of `regex-lite`.
regex = ["dep:regex"]

[target.'cfg(not(feature = "regex"))'.dependencies]
regex-lite = "0.1"

[lints]
workspace = true
