[package]
name = "flare3d-dummy-example"
version = "0.1.0"
edition = "2021"
authors = ["KrLite"]
description = "Dummy example of flare3d"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["game-development"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
flare3d = { path = "../../" }
winit = "0.26.0"
wgpu = "0.12.0"
pollster = "0.2"
