[package]
name = "rimecraft-edcode2"
version = "0.1.0"
edition = "2021"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Encode and Decode trait for PacketCodec implementations"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
bytes = "1.6"
rimecraft-edcode2-derive = { path = "../edcode2-derive", optional = true }

[features]
default = []
derive = ["dep:rimecraft-edcode2-derive"]

[lints]
workspace = true
