[package]
name = "rimecraft-state"
version = "0.1.0"
edition = "2021"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft state holders"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
regex = "1.10"
serde = { version = "1.0", optional = true }

[features]
serde = ["dep:serde"]

[lints]
workspace = true
