[package]
name = "rimecraft-state"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft state holders"
repository = "https://codeberg.org/DM-Earth/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-maybe = { path = "../../util/maybe" }
regex-lite = "0.1"
regex = { version = "1.10", optional = true }
serde = { version = "1.0", optional = true }
rimecraft-serde-update = { path = "../../util/serde-update", optional = true }
ahash = "0.8"
typeid = "1.0"
ident-hash = { path = "../../util/ident-hash", package = "rimecraft-ident-hash" }

[dev-dependencies]
static_assertions = "1.1"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:rimecraft-serde-update"]
# use `regex` crate instead of `regex-lite`.
regex = ["dep:regex"]

[lints]
workspace = true
