[package]
name = "rimecraft-option"
version = "0.1.0"
edition = "2021"
authors = ["KrLite"]
description = "Minecraft game options"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-text = { path = "../text" }
rimecraft-math = { path = "../../util/math" }

[lints]
workspace = true
