[package]
name = "rimecraft-math"
version = "0.1.0"
edition = "2024"
authors = ["KrLite", "JieningYu <jiening.yu@outlook.com>"]
description = "Math library for Rimecraft"
repository = "https://codeberg.org/DM-Earth/rimecraft/"
license = "AGPL-3.0-or-later"
categories = ["game-development"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
num-integer = "0.1"
num-traits = "0.2.19"

[lints]
workspace = true
