[package]
name = "rimecraft-entity"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft Entity primitives"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
global-cx = { path = "../global-cx", package = "rimecraft-global-cx" }
registry = { path = "../registry", package = "rimecraft-registry" }
dsyn = { path = "../../util/dsyn", package = "rimecraft-dsyn" }
uuid = "1.18"
erased-serde = "0.4"
serde = "1.0"
serde-update = { path = "../../util/serde-update", features = [
    "erased",
], package = "rimecraft-serde-update" }
serde-compat = { path = "../../util/serde-compat", features = [
    "uuid",
], package = "rimecraft-serde-compat" }
typeid = "1.0"
parking_lot = "0.12"
glam = { version = "0.30", features = ["serde"] }

[features]

[lints]
workspace = true
