[package]
name = "rimecraft-entity"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft Entity primitives"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
global-cx = { path = "../global-cx", package = "rimecraft-global-cx" }
registry = { path = "../registry", package = "rimecraft-registry" }
dsyn = { path = "../../util/dsyn", package = "rimecraft-dsyn" }

[features]

[lints]
workspace = true
