[package]
name = "rimecraft-identifier"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Rust implementation of Minecraft resource location"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
serde = { version = "1.0", optional = true }
rimecraft-edcode2 = { path = "../edcode2", optional = true }

[features]
default = ["vanilla"]
serde = ["dep:serde"]
edcode = ["dep:rimecraft-edcode2"]
vanilla = []

[lints]
workspace = true
