[package]
name = "rimecraft-item"
version = "0.1.0"
edition = "2021"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft item primitives"
repository = "https://github.com/rimecraft-rs/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-registry = { path = "../registry" }
rimecraft-fmt = { path = "../../util/fmt" }
rimecraft-attachment = { path = "../../util/attachment" }
rimecraft-serde-update = { path = "../../util/serde-update", optional = true }
rimecraft-serde-humanreadctl = { path = "../../util/serde-humanreadctl", optional = true }
fastnbt = "2.4"
rimecraft-nbt-ext = { path = "../../util/nbt-ext" }
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
# default = ["serde"]
serde = [
    "dep:serde",
    "rimecraft-registry/serde",
    "rimecraft-attachment/serde",
    "dep:rimecraft-serde-update",
    "dep:rimecraft-serde-humanreadctl",
]

[lints]
workspace = true
