[package]
name = "rimecraft-chunk-palette"
version = "0.1.0"
edition = "2024"
authors = ["JieningYu <jiening.yu@outlook.com>"]
description = "Minecraft chunk palettes"
repository = "https://codeberg.org/DM-Earth/rimecraft/"
license = "AGPL-3.0-or-later"
categories = []

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
rimecraft-packed-int-array = { path = "../../util/packed-int-array" }
rimecraft-maybe = { path = "../../util/maybe" }
edcode2 = { path = "../../util/edcode2", package = "rimecraft-edcode2", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
rimecraft-serde-update = { path = "../../util/serde-update", optional = true }
ahash = "0.8"

[dev-dependencies]
fastnbt = "2.6"
static_assertions = "1.1"

[features]
edcode = ["dep:edcode2"]
serde = ["dep:rimecraft-serde-update", "dep:serde"]

[lints]
workspace = true
